# Generated by Django 4.2.3 on 2023-08-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='suscribers',
            new_name='subscribers',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='suscribers_count',
            new_name='subscribers_count',
        ),
    ]
