# Generated by Django 4.2.3 on 2023-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_suscribers_page_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
