# Generated by Django 4.2.3 on 2023-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_story_is_expired'),
        ('page', '0003_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stories',
            field=models.ManyToManyField(blank=True, to='post.story'),
        ),
    ]
