# Generated by Django 4.2.3 on 2023-08-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_stories'),
        ('notification', '0002_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New friendrequuest'), ('accepted_friendrequest', 'Accepted friendrequest'), ('rejected_friendrequest', 'Rejected friendrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment'), ('page_liked', 'Page Liked'), ('page_post', 'Page Post'), ('page_admin', 'Page Admin')], max_length=50),
        ),
    ]
