# Generated by Django 4.2.3 on 2023-08-10 16:26

import django.core.validators
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postvideo_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'gif', 'MP4', 'AVI', 'MOV', 'GIF']), post.models.validate_file_size]),
        ),
    ]
