# Generated by Django 4.2.3 on 2023-08-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postvideo_video_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
