# Generated by Django 4.2.3 on 2023-08-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_story_expires_at_story_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_expired',
        ),
    ]
