# Generated by Django 4.2.3 on 2023-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
