# Generated by Django 4.2.3 on 2023-08-24 11:24

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_conversationmessage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to='voice_notes/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_voices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='chat_videos', validators=[chat.models.validate_file_size])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_attachments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='chat.chatattachment'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='videos',
            field=models.ManyToManyField(blank=True, to='chat.chatvideo'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='voices',
            field=models.ManyToManyField(blank=True, to='chat.chatvoice'),
        ),
    ]
